sudo: false
language: node_js
cache: false
notifications:
  email: false
node_js:
  - '4'
  - '6'
  - stable
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm run test:coverage && npm run test:coverage:upload
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
